### ISSUE TITLE
Type null 에러(1)

### ISSUE THREAD

**Issue by Kim-Gayoung** [Kim-Gayoung/RPCExample_Java#15]
https://github.com/Kim-Gayoung/RPCExample_Java/blob/8a1f0067b1c228638cb10bb502a9de431d8dc619/src/com/example/extrpc/Infer.java#L80

@kwanghoon 
위와 같은 라인에서 함수명의 타입을 찾기때문에 발생한 에러였습니다.
예를 들어
`main = getHour ()`
라는 간단한 예제에서 getHour는 Var이기 때문에 함수에 대한 타입을 찾으려 시도 하고 getHour에 대한 타입이 없어 null을 반환합니다.

이 문제는 프로그램에 함수 예제를 작성해주면 해결될 문제이지만,
readConsole, isNothing, writeFile 등과 같은 라이브러리 함수들에 대해 동일하게 적용할 수 없다는 문제점이 있습니다.

처음에 init과 같은 함수를 만들어 라이브러리 함수들에 대한 타입을 미리 정해놓는게 맞을까요??

**Comment by kwanghoon** [comment]
그렇지! 라이브러리 함수들의 타입은 미리 타입 환경에 가지고 있어야겠지.
이런 질문을 세미나 시간에 해야 했었지...
