### ISSUE TITLE
FunStore를 HashMap으로 구현하지 않고 ArrayList로 구현한 이유가 있나? 함수 호출할 때마다 매번 lookup을 할텐데. 

### ISSUE THREAD

**Issue by kwanghoon** [Kim-Gayoung/RPCExample_Java#4]
https://github.com/Kim-Gayoung/RPCExample_Java/blob/7c685e73d0a58caa9c2d280ec0f282d5a4d6cb1d/src/com/example/stacs/FunStore.java#L8
@Kim-Gayoung

**Comment by Kim-Gayoung** [comment]
@kwanghoon 
순서를 유지해야 된다고 생각해서 ArrayList를 사용하게 되었습니다. HashMap을 쓰게 된다면 나중에 출력으로 FunStore를 전달해줬을 때 값이 뒤죽박죽 섞여있어 값을 찾아 확인하기가 어려워질 것이라고 생각했습니다.

순서를 유지할 필요가 없다면 HashMap으로 수정하고, 순서를 유지해야 할 필요성이 생긴다면 LinkedHashMap으로 수정하겠습니다.

**Comment by Kim-Gayoung** [comment]
@kwanghoon 
list나 map을 통해서 입력할 때의 순서를 유지해야 된다고만 생각했던 것 같습니다.
key를 기준으로 sorting해서 출력하는 방향으로 수정하도록 하겠습니다.
