### ISSUE TITLE
evalClient의 두번째 인자가 ClientContext가 아니라 ServerContext

### ISSUE THREAD

**Issue by kwanghoon** [Kim-Gayoung/RPCExample_Java#5]
https://github.com/Kim-Gayoung/RPCExample_Java/blob/7c685e73d0a58caa9c2d280ec0f282d5a4d6cb1d/src/com/example/stacs/TypedCSSta.java#L62
@Kim-Gayoung

**Comment by Kim-Gayoung** [comment]
@kwanghoon 이 부분은 교수님께서 보내주셨던 수정된 논문에서 21페이지 위에서 4번째 문단과 그림 11번을 참조하여 작성했었습니다. 그 내용은 아래와 같은데

> call and ret are the only constructs to push onto and to pop from the server stack. ... every invocation of a client function from the server will return to the server without changing the client context and the server stack.

위와 같은 부분에서 Call과 Ret은 서버 스택에 값을 push하고 pop하는 구조라고 이해 해서 ClientContext가 아닌 ServerContext를 사용했습니다.

제가 잘못 이해한 부분이고 잘못 프로그래밍 된 부분이라면 수정하겠습니다.

**Comment by Kim-Gayoung** [comment]
@kwanghoon 
저는 Ctx x M이라는 표현이 'x에 값이 바인딩되고 M이 진행되어야 한다'라고 이해를 했습니다. 즉, Call이나 Request를 통해서 다른 location으로 넘어갔다 돌아왔을 때 진행해야할 상황을 저장한다고 생각했습니다.

그러나 위와 같은 부분에서 ClientContext가 아닌 ServerContext를 준 이유는 Client측에서 Server로 값을 반환할 때 ServerContext가 필요하며, ClientContext는 stack이 아니기에 매번 새로 생성을 해줘야 한다고 생각을 해 저렇게 작성하게 되었습니다.

**Comment by kwanghoon** [comment]
@Kim-Gayoung 잘 이해하고 있는 부분도 있고 잘못 이해하고 있는 부분도 있네. 
세미나 시간에 이 부분에 대해서 논의하기로 하고, 어쨋든 client는 client context를 server는 server context를 갖는 것이 맞고, 특히 Stateful CS calculus에서는 내가 참고하라고 본 Figure 9에서와 같이 Client context는 Ctx x m으로 스택이 아니고, Server context는 Ctx x1 m1 . Ctx x2 m2 .  ... . Ctx xn mn (n>=0)으로 스택이다.

**Comment by kwanghoon** [comment]
OK
